// AngularVideoPlayer/src/app/modules/management/management.component.ts
import { Component, OnInit } from '@angular/core';
import { VideoService } from 'src/app/services/video.service';
import { Video } from 'src/app/models/video.model';
import { FormGroup, FormBuilder, FormControl } from '@angular/forms';
// import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

@Component({
  selector: 'app-management',
  templateUrl: './management.component.html',
  styleUrls: ['./management.component.scss']
})
export class ManagementComponent implements OnInit {

  public videos: Video[];
  isEditable = {};
  public addVideoFormGroup: FormGroup;

  constructor(
    private videoService: VideoService,
    private formBuilder: FormBuilder,
  ) { }

  ngOnInit() {
    this.loadVideos();
    this.buildFormGroup();
  }

  // TODO Need to add validations
  private buildFormGroup() {
    this.addVideoFormGroup = this.formBuilder.group({
      id: new FormControl(),
      title: new FormControl(),
      url: new FormControl()
    });
  }

  private loadVideos() {
    this.videoService.getVideos().subscribe(
      videos => this.videos = videos
    );
  }

  delete(row, rowIndex) {
    this.videoService.deleteVideo(row.id).subscribe(
      () => this.loadVideos()
    );
  }

  // Save row
  save(row, rowIndex) {
    this.isEditable[rowIndex] = !this.isEditable[rowIndex];
    this.videoService.updateVideo(row).subscribe(
      () => this.loadVideos()
    );
  }

  addNewVideo() {
    const newVideo: Video = {
      id: Number(this.getFormValue('id')),
      title: this.getFormValue('title'),
      url: this.getFormValue('url'),
      like: 0,
      unlike: 0
    };
    this.videoService.addVideo(newVideo).subscribe(
      () => this.loadVideos()
    );
  }

  private getFormValue(controlName) {
    return this.addVideoFormGroup.controls[controlName].value;
  }
}

<h2>Add new video</h2>
<div class="row">
  <div class="col-lg-6 mt-2">
    <form [formGroup]="addVideoFormGroup" (ngSubmit)="addNewVideo()">
      <div class="form-group">
        <label style="color: white">ID:</label>
        <input type="text" class="form-control" formControlName="id" placeholder="Enter ID">
        <div *ngIf="id.invalid && (id.dirty || id.touched)" class="alert alert-danger">
          <div *ngIf="id.errors.required">
            ID is required
          </div>
          <div *ngIf="id.errors.pattern">
            ID should be number
          </div>
        </div>            
      </div>  
      <div class="form-group">
        <label style="color: white">Title:</label>
        <input type="text" class="form-control" formControlName="title" placeholder="Enter Title">
        <div *ngIf="title.invalid && (title.dirty || title.touched)" class="alert alert-danger">
          <div *ngIf="title.errors.required">
            Title is required
          </div>
        </div>
      </div>
      <div class="form-group">
        <label style="color: white">Youtube URL:</label>
        <input type="url" class="form-control" formControlName="url" autocomplete="off" placeholder="Enter URL">
        <div *ngIf="url.invalid && (url.dirty || url.touched)" class="alert alert-danger">
          <div *ngIf="url.errors.required">
            URL is required
          </div>
          <div *ngIf="url.errors.pattern">
            URL is invalid
          </div>
        </div>        
      </div>
      <button type="submit" class="btn btn-primary">Add Video</button>
    </form>
  </div>
</div>

<h2>Edit video</h2>
<ngx-datatable class='material' [headerHeight]="50" [footerHeight]="50" [rowHeight]="'auto'"
  [limit]="10" [rows]='videos'>
  <ngx-datatable-column [resizeable]="false" [width]="45" [sortable]="true" name="name">
    <ng-template let-column="column" ngx-datatable-header-template>
      S.no
    </ng-template>
    <ng-template let-row="row" ngx-datatable-cell-template>
      {{row.id}}
    </ng-template>
  </ngx-datatable-column>
  <ngx-datatable-column [resizeable]="false" [width]="100" >
    <ng-template let-column="column" ngx-datatable-header-template>
      Title
    </ng-template>
    <ng-template let-row="row" let-rowIndex="rowIndex" ngx-datatable-cell-template>
      <div *ngIf="isEditable[rowIndex]">
          <input class="form-control" type="text" [(ngModel)]="row.title" [disabled]="!isEditable[rowIndex]">  
      </div>
      <div *ngIf="!isEditable[rowIndex]">
        {{row.title}}
      </div>
    </ng-template>
  </ngx-datatable-column>
  <ngx-datatable-column [resizeable]="false" [width]="500" >
    <ng-template let-column="column" ngx-datatable-header-template>
      URL
    </ng-template>
    <ng-template let-row="row" let-rowIndex="rowIndex" ngx-datatable-cell-template>
      <div *ngIf="isEditable[rowIndex]">
          <input class="form-control" type="text" [(ngModel)]="row.url" [disabled]="!isEditable[rowIndex]">  
      </div>
      <div *ngIf="!isEditable[rowIndex]">
        {{row.url}}
      </div>
    </ng-template>
  </ngx-datatable-column>
  <ngx-datatable-column [resizeable]="false" [width]="300" >
    <ng-template let-column="column" ngx-datatable-header-template>
      Action
    </ng-template>
    <ng-template let-row="row" let-rowIndex="rowIndex" ngx-datatable-cell-template>
      <div class="actions-container">
        <div class="action">
          <button class="btn btn-dark" (click)="this.isEditable[rowIndex]=!this.isEditable[rowIndex]"
          [disabled]="isEditable[rowIndex]">
            Edit</button>
        </div>
        <div class="action">
          <button class="btn btn-danger" (click)="delete(row, rowIndex);">Delete</button>
        </div>
        <div class="action">
          <button class="btn btn-primary" (click)="save(row, rowIndex);" [disabled]="!isEditable[rowIndex]">
            Approve</button>
        </div>
      </div>
    </ng-template>
  </ngx-datatable-column>
</ngx-datatable>

// react-video-player/src/components/Management.js
import React from 'react';
import videoService from '../services/videoService';
import emitter from "../services/playerService";

class Management extends React.Component {
  constructor (props) {
    super(props)
    this.state = {
      videos: [],
      id: '',
      title: '',
      url: '',
      isCurrentRowEditable: false
    }
    this.handleChange = this.handleChange.bind(this)
    this.handleSubmit = this.handleSubmit.bind(this)
  }

  handleChange(event) {
    this.setState({ 
      [event.target.name]: event.target.value
    })
  }

  handleSubmit(event) {
    const newVideo = {
      id: Number(this.state.id),
      title: this.state.title,
      url: this.state.url,
      like: 0,
      unlike: 0
    }
    videoService.createVideo(newVideo)
      .then(response => {
        this.resetInput();
        this.refreshVideos();
      });
    event.preventDefault();
  }

  resetInput = () => {
    this.setState({
      id: '',
      title: '',
      url: ''
    });
  }

  componentWillMount() {
    this.refreshVideos();
  }

  refreshVideos() {
    videoService.getVideos()
    .then(response => response.json())
    .then(videos => {
      this.setState({
        videos: videos
      })
      // Notify the PlayList to update the video list.
      emitter.emit('onRefreshVideos', videos);
    })
  }

  onEditRow(video){
    this.setState({
      isCurrentRowEditable: true,
      currentRowId: video.id,
    });
  }

  onDeleteVideo(video) {
    if (window.confirm(`Are you sure to remove the video ${video.title}?`)) {
      videoService.deleteVideo(video.id)
        .then(response => this.refreshVideos());
    }
  }

  onApprove(video) {
    const title = this.state.rowTitle || video.title; 
    const url = this.state.rowUrl || video.url;

    const currentRowId = Number(this.state.currentRowId);
    let toBeUpdatedVideo = this.state.videos.filter(v => v.id === currentRowId)[0];

    toBeUpdatedVideo.title = title;
    toBeUpdatedVideo.url = url;
    console.log(toBeUpdatedVideo);
    videoService.updateVideo(toBeUpdatedVideo.id, toBeUpdatedVideo)
      .then(response => {
        this.refreshVideos()
        this.setState({
          isCurrentRowEditable: false
        });
      });
  }

  render() {
    return (
      <div>
        <h2>Add new video</h2>
        <div className="row">
          <div className="col-lg-6 mt-2 mb-5">
            <form onSubmit={this.handleSubmit}>
              <div className="form-group">
                <label>ID:</label>
                <input type="text" className="form-control" 
                  value={this.state.id} name="id" onChange={this.handleChange} placeholder="Enter ID" />
              </div>  
              <div className="form-group">
                <label>Title:</label>
                <input type="text" className="form-control" 
                  value={this.state.title} name="title" onChange={this.handleChange} placeholder="Enter Title" />
              </div>
              <div className="form-group">
                <label>Youtube URL:</label>
                <input type="url" className="form-control" 
                  value={this.state.url} name="url" onChange={this.handleChange} autoComplete="off" placeholder="Enter URL" />
              </div>
              <button type="submit" className="btn btn-primary">Add Video</button>
            </form>
          </div>
        </div>        
        <div className="row">
          <table className="table table-dark">
            <thead>
              <tr>
                <th scope="col">S.no</th>
                <th scope="col">Title</th>
                <th scope="col">Url</th>
                <th scope="col">Actions</th>
              </tr>
            </thead>
            <tbody>
              {
                this.state.videos.map(
                  video => 
                  <tr key={video.id}>
                    <th scope="row">
                      <label>{video.id}</label>
                    </th>
                    <td>
                      {
                        this.state.isCurrentRowEditable && video.id === this.state.currentRowId 
                        ? 
                        <input className="form-control" type="text" name="rowTitle"
                          onChange={this.handleChange} 
                          value={this.state.rowTitle ? this.state.rowTitle : video.title} />
                        :
                        <label>{video.title}</label>
                      }
                    </td>
                    <td>
                    {
                        this.state.isCurrentRowEditable && video.id === this.state.currentRowId 
                        ? 
                        <input className="form-control" type="text" name="rowUrl"
                          onChange={this.handleChange} 
                          value={this.state.rowUrl ? this.state.rowUrl : video.url} />
                        :
                        <label>{video.url}</label>
                      }
                    </td>
                    <td>
                      <div className="actions-container">
                        <div className="action">
                          <button className="btn btn-light" type="button" onClick={(e) => this.onEditRow(video)}>
                            Edit</button>
                        </div>
                        <div className="action">
                          <button className="btn btn-danger" type="button" onClick={() => this.onDeleteVideo(video)}>
                            Delete</button>
                        </div>
                        <div className="action">
                          <button className="btn btn-primary" 
                            disabled={!(this.state.isCurrentRowEditable && video.id === this.state.currentRowId) } 
                            type="button" onClick={(e) => this.onApprove(video)}>
                            Approve</button>
                        </div>  
                      </div>  
                    </td>
                  </tr>
                )
              }
            </tbody>
          </table>            
        </div>  
      </div>      
    );
  }
}

export default Management;
