// react-video-player/src/components/Playlist.js
import React from 'react';
import emitter from "../services/playerService";
import videoService from '../services/videoService';

class Playerlist extends React.Component {
  constructor () {
    super()
    this.state = {
      videos: []
    }
    // this.onPlay = this.onPlay.bind(this)
  }
  
  componentWillMount() {
    videoService.getVideos()
    .then(response => response.json())
    .then(videos => {
      this.setState({
        videos: videos
      })
    })
  }

  onPlay(video) {
    this.setState({
      isPlaying: true
    })
    console.log(video);
    emitter.emit("switch", video);
  }

  render() {
    return (
      <div className="media-player-list">
      <h2>Play list</h2>
      <ul className="list-group list-group-flush">
        {
          this.state.videos.map(
            video => 
            <li className="list-group-item" key={video.id} onClick={() => this.onPlay(video)}>
              <i className="fas fa-video playlistItem"></i>
              {video.title}
          </li>
          )
        }
      </ul>
    </div>
    );
  }
}

export default Playerlist;

// AngularVideoPlayer/src/app/modules/playlist/playlist.component.ts
import { Component, OnInit } from '@angular/core';
import { Video } from 'src/app/models/video.model';
import { VideoService } from 'src/app/services/video.service';
import { PlayerService } from 'src/app/services/player.service';

@Component({
  selector: 'app-playlist',
  templateUrl: './playlist.component.html',
  styleUrls: ['./playlist.component.scss']
})
export class PlaylistComponent implements OnInit {

  public videos: Video[];
  constructor(
    private videoService: VideoService,
    private playerService: PlayerService) { }

  ngOnInit() {
    this.loadVideos();
  }

  private loadVideos() {
    this.videoService.getVideos().subscribe(
      videos => this.videos = videos
    );
  }

  onPlay(video: Video) {
    this.playerService.switchVideoEvent.emit(video);
  }

}

<div class="media-player-list">
  <h2>Play list</h2>
  <ul class="list-group list-group-flush">
      <li class="list-group-item" *ngFor="let video of videos;" (click)="onPlay(video)">
          <i class="fas fa-video" style="margin-right: 2em;"></i>
          {{video.title}}
      </li>
  </ul>
</div>
