// react-video-player/src/components/Player.js
import React from 'react';
import emitter from "../services/playerService";

class Player extends React.Component {
  videoPlayerRef = React.createRef();
  constructor(props) {
    super(props);
    this.state = {
        msg: null,
    };
  }
  componentDidMount() {
    this.eventEmitter = emitter.addListener("onPlay", () => {
      this.videoPlayerRef.current.play();
    }).addListener("onPause", () => {
      this.videoPlayerRef.current.pause();
    }).addListener("onStop", () => {
      this.videoPlayerRef.current.pause();
      this.videoPlayerRef.current.currentTime = 0;
    }).addListener("onVolumeUp", (state) => {
      this.videoPlayerRef.current.volume = state.volume;
    }).addListener("onVolumeDown", (state) => {
      this.videoPlayerRef.current.volume = state.volume;
    }).addListener("onMute", () => {
      this.videoPlayerRef.current.muted = true;
    }).addListener("onUnMute", () => {
      this.videoPlayerRef.current.muted = false;
    }).addListener("switch", (video) => {
      this.videoPlayerRef.current.src = video.url;
      this.videoPlayerRef.current.play();
    })
  }

  onTimeUpdate() {
    const percentage = Math.floor((100 / this.videoPlayerRef.current.duration)
      * this.videoPlayerRef.current.currentTime);
    emitter.emit('timeupdate', percentage); 
  }

  componentWillUnmount(){
    emitter.removeListener(this.eventEmitter);
  }

  render() {
    return (
      <div className="playerWrapper">
        { this.state.msg }
        <video loop autoPlay muted className="media-video" 
          onTimeUpdate={()=>this.onTimeUpdate()} ref={this.videoPlayerRef} >
          <source src="http://vjs.zencdn.net/v/oceans.mp4" />
        </video>
      </div>
    );
  }
}

export default Player;

// AngularVideoPlayer/src/app/modules/player/player.component.ts
import { Component, OnInit, OnDestroy, ElementRef } from '@angular/core';
import { PlayerService } from 'src/app/services/player.service';
import { PlayerEvent, VideoPlayer } from 'src/app/models/player.model';
import { Subscription } from 'rxjs';

@Component({
  selector: 'app-player',
  templateUrl: './player.component.html',
  styleUrls: ['./player.component.scss']
})
export class PlayerComponent implements OnInit, OnDestroy {

  private controlEventsSubscribe: Subscription;

  constructor(
    private el: ElementRef,
    private playerService: PlayerService) {}

  ngOnInit() {
    // Add event for timeupdate during playing video
    this.controlEventsSubscribe = this.el.nativeElement.querySelector('.media-video')
      .addEventListener('timeupdate', () => {
        // console.log(this.playerService.VideoPlayer.currentTime);
        const percentage = Math.floor((100 / this.playerService.VideoPlayer.duration)
         * this.playerService.VideoPlayer.currentTime);
        console.log('percentage', percentage);
        this.playerService.videoPercentageUpdateEvent.emit(percentage);
    });

    // Set up the videoPlayer instance in playerService
    this.playerService.VideoPlayer = this.el.nativeElement.querySelector('.media-video');

    this.playerService.controlEvents.subscribe((event: PlayerEvent) => {
      switch (event) {
        case PlayerEvent.PLAY:
          this.playerService.VideoPlayer.play();
          break;

        case PlayerEvent.PAUSE:
          this.playerService.VideoPlayer.pause();
          break;

        case PlayerEvent.STOP:
          this.handleStopEvent();
          break;

        case PlayerEvent.MUTE:
          this.handleMuteEvent();
          break;

        case PlayerEvent.VOLUME_CHANGE:
          this.handleVolumeChange();
          break;
      }
    });
  }

  ngOnDestroy() {
    this.controlEventsSubscribe.unsubscribe();
  }

  private handleMuteEvent() {
    this.playerService.VideoPlayer.muted = !this.playerService.VideoPlayer.muted;
  }

  private handleVolumeChange() {
    this.playerService.VideoPlayer.volume = this.playerService.Volume;
  }

  private handleStopEvent() {
    this.playerService.VideoPlayer.pause();
    this.playerService.VideoPlayer.currentTime = 0;
  }

}

<div style="display: block">
  <video class="media-video">
    <source src="http://vjs.zencdn.net/v/oceans.mp4" >
  </video>
</div>
